---

- assert:
    that:
      - BASHRC is defined
      - BASHRC_FILE is defined
      - BASH_PROFILE is defined
      - BASH_PROFILE_FILE is defined
      - ZSHRC is defined
      - ZSHRC_FILE is defined
      - ZPROFILE is defined
      - ZPROFILE_FILE is defined
      - PYENVRC is defined
      - PYENV_DIR is defined
      - PYENV_VERSION is defined
    msg: required variables are not defined.

- name: Copy .bashrc
  copy:
    dest: "{{ BASHRC_FILE }}"
    content: "{{ BASHRC }}"

- name: Copy .bash_profile
  copy:
    dest: "{{ BASH_PROFILE_FILE }}"
    content: "{{ BASH_PROFILE }}"

- name: Copy .zshrc
  copy:
    dest: "{{ ZSHRC_FILE }}"
    content: "{{ ZSHRC }}"

- name: Copy .zprofile
  copy:
    dest: "{{ ZPROFILE_FILE }}"
    content: "{{ ZPROFILE }}"


- name: Check if pyenv is installed
  stat:
    path: "{{ PYENV_DIR }}"
  register: r
  ignore_errors: true

- block:

    - name: Ensure pyenv setting in ~/.zshrc
      blockinfile:
        insertafter: '# --PYENV--'
        path: "{{ ZSHRC_FILE }}"
        content: "{{ PYENVRC }}"

    - name: Check if python is installed under pyenv
      stat:
        path: "{{ PYENV_DIR + '/versions/' + PYENV_VERSION }}"
      register: version_check
      ignore_errors: true

    - name: Ensure pyenv version setting in ~/.zshrc
      lineinfile:
        insertafter: '# --PYENV_VERSION--'
        path: "{{ ZSHRC_FILE }}"
        regexp: '^pyenv global'
        line: "{{ 'pyenv global ' + PYENV_VERSION }}"
      when:
        - version_check.stat.exists

    - name: Use system python
      lineinfile:
        insertafter: '# --PYENV_VERSION--'
        path: "{{ ZSHRC_FILE }}"
        regexp: '^pyenv global'
        line: pyenv global system
      when:
        - not version_check.stat.exists

  when:
    - r.stat.exists
