---

#
# 実行前チェック
#
- name: Validate ansible environment
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/vars.yml
    - vars/vault.yml
  tasks:

    - debug:
        msg: "{{ PROXYRC }}"

    - name: FAIL SCRIPT IF REQUIRED TARGET_HOSTS PARAMETER IS MISSING
      fail:
        msg: "You have to add the 'TARGET_HOSTS:' in vars.yml"
      when:
        - (TARGET_HOSTS is not defined) or (TARGET_HOSTS == '')

    # 引数なしでの実行はエラーにする
    - fail:
        msg: |
          タグの指定が必要です。
           -t config
           ---------
             -t osx
             -t ssh
             -t git
             -t bash
             -t proxy
             -t emacs
           ---------
           -t pyenv
           -t brew
           -t node
           -t vscode
           -t mas

#
# 実行
#
- name: Setup macOS
  hosts: "{{ TARGET_HOSTS }}"
  # factsを収集しないと使えない変数がある
  gather_facts: true
  vars_files:
    - vars/vars.yml
    - vars/vault.yml
  tasks:

    # osx defaults
    - import_role:
        name: osx_defaults
      tags:
        - osx
        - config

    # ~/.ssh/config
    - import_role:
        name: ssh
      tags:
        - ssh
        - config

    # ~/.gitconfig
    - import_role:
        name: git
      tags:
        - git
        - config

    # ~/.bashrc ~/.bash_profile
    - import_role:
        name: bash
      tags:
        - bash
        - config

    # ~/.proxyrc
    - import_role:
        name: proxy
      when:
        - USE_PROXY
      tags:
        - proxy
        - config

    # brew
    - import_role:
        name: brew
      tags:
        - brew
        - config

    # emacs
    - import_role:
        name: emacs
      tags:
        - emacs
        - config

    # pyenv
    - import_role:
        name: pyenv
      tags:
        - pyenv

    # node
    - import_role:
        name: node
      tags:
        - node

    # mas
    - import_role:
        name: mas
      tags:
        - mas

    # vscode
    - import_role:
        name: vscode
      tags:
        - vscode
