---

- assert:
    that:
      - PROXYRC is defined
      - NO_PROXYRC is defined
      - PROXYRC_FILE is defined
      - NO_PROXYRC_FILE is defined
    msg: required variables are not defined.


- name: Copy .proxyrc
  copy:
    dest: "{{ PROXYRC_FILE }}"
    content: "{{ PROXYRC }}"

- name: Copy .noproxyrc
  copy:
    dest: "{{ NO_PROXYRC_FILE }}"
    content: "{{ NO_PROXYRC }}"

- name: Set proxy config in ~/.bashrc
  lineinfile:
    path: "{{ BASHRC_FILE }}"
    insertafter: '# --PROXY--'
    line: '. ~/.proxyrc'
  when: USE_PROXY
