---

- assert:
    that:
      - PROXYRC is defined
      - PROXYRC_FILE is defined
      - PROXYRC_FILE is defined
    msg: required variables are not defined.


- block:

    - name: Copy .proxyrc
      copy:
        dest: "{{ PROXYRC_FILE }}"
        content: "{{ PROXYRC }}"

    - name: Set proxy config in ~/.bashrc
      lineinfile:
        path: "{{ BASHRC_FILE }}"
        insertafter: '# --PROXY--'
        line: '. ~/.proxyrc'

  when: USE_PROXY
