---

- name: Create .nodebrew dir if not exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ NODEBREW_DIR }}"
    - "{{ NODEBREW_SRC_DIR }}"

- name: Check if Node.js is installed
  shell: which node
  ignore_errors: True
  changed_when: False
  register: nodejs_installed

- name: インストール済みのnode.jsのバージョンを確認
  shell: nodebrew ls
  ignore_errors: True
  changed_when: False
  when: nodejs_installed is success
  register: nodejs_target_version_exist

- name: node.jsをインストール
  shell: nodebrew install-binary "{{ nodebrew_nodejs_version }}"
  when: (nodejs_installed|failed) or (nodejs_target_version_exist|failed)

- name: 使用するnode.jsのバージョンを指定
  shell: nodebrew use "{{ nodebrew_nodejs_version }}"
  when: (nodejs_installed|failed) or (nodejs_target_version_exist|failed)

- name: npm update
  shell: npm update -g npm
  when: nodebrew_npm_update



- name: Install npm packages global
  npm:
    name: "{{ item }}"
    global: true
  with_items:
    - "{{ NPM_PACKAGES }}"
