---

- assert:
    that:
      - MAS_PACKAGES is defined
    msg: required variables are not defined.


- name: Install apple store applications
  shell: /usr/local/bin/mas install {{ item.id }}
  with_items: "{{ MAS_PACKAGES }}"

- name: Upgrade applications
  shell: /usr/local/bin/mas upgrade
