---

- assert:
    that:
      - BREW_TAPS is defined
      - BREW_CASK_APPS is defined
      - BREW_PACKAGES is defined
    msg: required variables are not defined.


- name: Check brew is installed
  stat:
    path: /usr/local/bin/brew
  register: r

- assert:
    that:
      - r.stat.exists
    msg: brew is not installed.


# -
#   block:
#
#     - name: Get brew installer
#       get_url: url=https://raw.githubusercontent.com/Homebrew/install/master/install.sh dest=/tmp/brew_install.sh
#
#     - name: Install homebrew
#       command: yes \'\' | /bin/bash /tmp/brew_install.sh
#       become: true
#
#   when:
#     - not r.stat.exists


- name: Update homebrew
  homebrew:
    update_homebrew: true

- name: Update homebrew tap
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ BREW_TAPS }}"

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir=/Applications"
    accept_external_apps: true
  with_items: "{{ BREW_CASK_APPS }}"

- name: Install homebrew packages
  homebrew:
    name: "{{ BREW_PACKAGES }}"
    state: present

