---

- name: Copy ~/.emacs.d
  copy:
    src: "{{ ansible_user_dir + '/.emacs.d' }}"
    dest: "{{ ansible_user_dir }}"
    mode: 0600

- name: Copy ~/e-lisp
  copy:
    src: "{{ ansible_user_dir + '/e-lisp' }}"
    dest: "{{ ansible_user_dir }}"
    mode: 0600
