---

- assert:
    that:
      - OSX_DEFAULTS_LIST is defined
    msg: required variables are not defined.


- name: Write maxOS defaults settings
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - "{{ OSX_DEFAULTS_LIST }}"
