---

- assert:
    that:
      - ZSHRC_FILE is defined
      - PYENVRC is defined
      - PYENV_DIR is defined
      - PYENV_VERSION is defined
      - PIP_MODULES is defined
    msg: required variables are not defined.

- name: Check if pyenv is installed
  stat:
    path: "{{ PYENV_DIR }}"
  register: pyenv_directory

- block:

    - name: Install pyenv by git
      git:
        repo: git://github.com/pyenv/pyenv.git
        dest: "{{ PYENV_DIR }}"
        accept_hostkey: true

    - name: Ensure pyenv setting in ~/.zshrc
      blockinfile:
        insertafter: '# --PYENV--'
        path: "{{ ZSHRC_FILE }}"
        content: "{{ PYENVRC }}"
      notify: source zshrc

  when:
    - not pyenv_directory.stat.exists

- name: Check if python "{{ PYENV_VERSION }} is installed"
  stat:
    path: "{{ PYENV_DIR + '/versions/' + PYENV_VERSION }}"
  register: version_directory
  ignore_errors: true

- block:

    # 2019/02/17時点
    # macOS Mojave 10.14以降だとpyenvでPythonをインストールする際にエラーが出るのでその対策
    # becomeがうまく機能しないので、手で実行しておく。もともと一度やればすむことなので。
    # - name: Install macOS_SDK_headers_for_macOS_10.14.pkg
    #   shell: installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
    #   become: true

    - name: Install python "{{ PYENV_VERSION }}"
      shell: 'zsh -lc "pyenv install {{ PYENV_VERSION }}"'

    - name: Switch python version to "{{ PYENV_VERSION }}"
      shell: 'zsh -lc "pyenv global {{ PYENV_VERSION }}"'

    - name: Ensure pyenv version setting in ~/.zshrc
      lineinfile:
        insertafter: '# --PYENV_VERSION--'
        path: "{{ ZSHRC_FILE }}"
        regexp: '^pyenv global'
        line: "{{ 'pyenv global ' + PYENV_VERSION }}"
      notify: source zshrc

  when:
    - not version_directory.stat.exists

- set_fact:
    ansible_python_interpreter: "{{ PYENV_DIR + '/shims/python' }}"

- name: Install python modules
  pip:
    name: "{{ PIP_MODULES }}"
  ignore_errors: true
